### ISSUE TITLE
Change categorieId to match the tutorial

### ISSUE THREAD

**Issue by sraza-onshape** [charlypoly/graphql-mesh-docs-first-gateway#17]
Hello, this is a small nitpick error:

On this [page](https://the-guild.dev/graphql/mesh/docs/getting-started/your-first-mesh-gateway) of the tutorial, we are given this example query for the Books service:

```
{
  books {
    authorId
    categoryId  // <-- this is the issue
    id
    title
  }
}
```

I just wanted to inform you that out of the box, this does not work. The error is because the [field](https://github.com/charlypoly/graphql-mesh-docs-first-gateway/blob/599c36c4660dfdea30fa4163d4a847698eb92c5e/packages/books-service/src/entities/Book.ts#L11) in the `Book` schema is called `categorieId`, not `categoryId`. Which might cause some confusion to readers.

**Comment by ardatan** [comment]
Would you create a PR for this change? Thanks!

**Comment by sraza-onshape** [comment]
> Would you create a PR for this change? Thanks!

Would it be enough for a PR to just replace all instances of the `categorieId` string with `categoryId`? Or do you think it'd require additional code changes @ardatan ?

**Comment by ardatan** [comment]
Updated! Thanks for the feedback!
