### ISSUE TITLE
Fix documentation and dependencies

### ISSUE THREAD

**Issue by Marx2** [charlypoly/graphql-mesh-docs-first-gateway#25]
after cloning project on Mac with M1 it doesn't work OOTB

- authors-service: grpc-tools version needs to be set as 1.12.4 (earlier versions are not compatible with M1)
- in some packages folders there are missing "dist" subfolder (can be empty, just build refuses to create file if no folder exists)
- forced node version is 17, I've downgraded mine with "nvm" to match
- you need to first issue "yarn" command, then "yarn workspaces run build"

Would be nice to upgrade this project to newest versions of graphl-mesh, as it misses essential examples like batching

**Comment by ardatan** [comment]
> authors-service: grpc-tools version needs to be set as 1.12.4 (earlier versions are not compatible with M1)
I don't use M1 or any other Mac specific CPUs but I've never heard this kind of issue from my colleagues. Maybe this issue has gone after our changes in the repo.

> in some packages folders there are missing "dist" subfolder (can be empty, just build refuses to create file if no folder exists)
You were supposed to run `build` first but now it is not required. There is no build step in any of examples here.

> forced node version is 17, I've downgraded mine with "nvm" to match
We'd recommend to use the LTS versions of Node.js. We don't test other versions that reached EOL, so I am not sure. Maybe you should try 18 instead

> you need to first issue "yarn" command, then "yarn workspaces run build"
Just added.

Closing this issue for now. Let us know if you still have issues :)
