### ISSUE TITLE
Please add "concurrently" to dependencies/documentation

### ISSUE THREAD

**Issue by bastman** [charlypoly/graphql-mesh-docs-first-gateway#7]
Hi, 

it looks like one has to install "concurrently" before "$ yarn run start-single-source".

Would you mind adding it the README.md or package.json

Thanks a lot

**Comment by charlypoly** [comment]
Hi @bastman,

`concurrently` is already added as a dependency:

https://github.com/charlypoly/graphql-mesh-docs-first-gateway/blob/599c36c4660dfdea30fa4163d4a847698eb92c5e/package.json#L20-L22

Did you run `yarn` before running `yarn run start-single-source`?
